name: binder-environment
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pip:
    - git+https://github.com/morphomatics/morphomatics.git#egg=morphomatics
    - pyvista
    - ipygany
    - ipywidgets
