site_name: Morphomatics
theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: amber
  logo: images/logo.png
repo_url: https://github.com/morphomatics/morphomatics
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - Home: index.md
    - Tutorial:
        - Shape Space: tutorial_shape_space.md
        - Statistical Shape Modeling: tutorial_ssm.md
        - Regression: tutorial_regression.md
        - Statistics in Lie groups: tutorial_biinvariant_statistics.md
    - Imprint: imprint.md
