site_name: Morphomatics
theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: amber
  logo: images/logo.png
  favicon: images/favicon.png
repo_url: https://github.com/morphomatics/morphomatics
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - mkdocs-jupyter
nav:
    - Home: index.md
    - Tutorial:
        - Shape Space: tutorials/tutorial_shape_space.ipynb
        - Statistical Shape Modeling: tutorials/tutorial_ssm.ipynb
        - Regression: tutorials/tutorial_regression.ipynb
        - Statistics in Lie groups: tutorials/tutorial_biinvariant_statistics.ipynb
        - Bézierfold: tutorials/tutorial_bezierfold.ipynb
    - Imprint: imprint.md
